console.log("2"+2);//22
console.log(null>0);//false
console.log(null==0);//false
console.log(null>=0);//true
console.log("2"+2+2);//222
console.log(2+"1"+3);//213
console.log(undefined==0);//false
console.log(undefined==null);//true
console.log(undefined>null);//false
